env: 
  global: 
    secure: QpP600DG8GcbqkmzssBXkttqCoikTI1REQHUfLv657HE/rpXvRXs5KHtV3lp5Sa0IdgHzczZ5AUwwq6w8MSybgqJCSMst+LMDxXw6Ue+icNRqmXn1LSP3Z4qBThgKPz9IJPbuyDAoEAxI1Uv7tktJg4XQtPSRz7pKEldEyvWIOo=

language: node_js

after_success:
  - git init gh-pages
  - cp -R app/* gh-pages/
  - cd gh-pages  
  - git config --global user.email "simone.busoli@gmail.com"
  - git config --global user.name "Travis-CI"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
  - git remote add origin https://github.com/simoneb/conmon.git
  - git add -A
  - git commit -m "Updating gh-pages"
  - git push -f origin gh-pages
    